#!/bin/bash  
ocamlbuild Main.byte &&
FILES=./Evaluator/*
for f in $FILES
do
  echo -e "\033[31m Unit test of $f ..."
  # take action on each file. $f store current file name
  echo -e "\033[0m"
  ./_build/Main/Main.byte $f
done
