exception ClassAlreadyExists of string
exception AttributeAlreadyExists of string
exception ArgumentAlreadyExists of string
exception MethodAlreadyExists of string
exception ConstructorAlreadyExists of string